[global]
proxy = http://12.26.204.100:8080
cert = /usr/share/ca-certificates/McAfee_CErtificate.cert
trusted-host = pypi.pythone.org
               pypi.org
               files.pythonhosted.org
               